### ISSUE TITLE
help to understand task_access

### ISSUE THREAD

**Issue by dcyou** [LaravelDaily/Laravel-Jetstream-CRUD-Roles#2]
Hi, 
I am looking your project and I can't understand how work the `task_access` Gate.
you have a `permission` table with that rule but I don't understand how it is apply

**Comment by PovilasKorop** [comment]
@dcyou please watch this video demo: https://www.youtube.com/watch?v=pyOcSEkG4Q0
If it answers your question, please close the issue

**Comment by dcyou** [comment]
explain at 14min, excellent thanks
